basePath: /v1
definitions:
  handler.ErrorResponse:
    properties:
      code:
        example: INVALID_REQUEST
        type: string
      details:
        example:
        - aaa
        - bbb
        - ccc
        items:
          type: string
        type: array
      message:
        example: 不正なリクエストです
        type: string
    type: object
  handler.GetSampleResponse:
    properties:
      id:
        example: "11111"
        type: string
      name:
        example: サンプル1
        type: string
    type: object
  handler.GetSurveyorsResponse:
    properties:
      id:
        example: "000001"
        type: string
      name:
        example: 調査員1
        type: string
      office:
        description: omitemptyをつけると、nilの場合はJSONに出力されません
        example: 札幌事業所
        type: string
      office-id:
        example: XX
        type: string
    type: object
info:
  contact: {}
  title: react-ts backend API
  version: "1.0"
paths:
  /samples:
    get:
      parameters:
      - in: query
        name: dateUtc
        type: string
      - in: query
        name: email
        type: string
      - collectionFormat: csv
        in: query
        items:
          type: integer
        name: intArray
        type: array
      - in: query
        name: q1
        required: true
        type: string
      - in: query
        maxLength: 3
        minLength: 2
        name: q2
        type: string
      - in: query
        name: uuid
        type: string
      responses:
        "200":
          description: 取得結果
          schema:
            $ref: '#/definitions/handler.GetSampleResponse'
        "400":
          description: 不正なリクエスト
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: 想定外のエラー
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: 実験用
      tags:
      - samples
  /surveyors:
    get:
      parameters:
      - example: "000001"
        in: query
        maxLength: 6
        name: id
        type: string
      - example: XX
        in: query
        maxLength: 2
        name: office-id
        type: string
      - description: 表示形式を指定するパラメータ
        enum:
        - basic
        - detail
        example: detail
        in: query
        name: view
        type: string
      responses:
        "200":
          description: 調査員のリスト
          schema:
            items:
              $ref: '#/definitions/handler.GetSurveyorsResponse'
            type: array
        "400":
          description: 不正なリクエスト
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: 想定外のエラー
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: 指定した事業所の調査員のリストを返す
      tags:
      - surveyors
swagger: "2.0"
